### ISSUE TITLE
do we have support for 3.7? 

### ISSUE THREAD

**Issue by palomamtnez** [naboo/craft-siteduplicate#6]

**Comment by naboo** [comment]
Sorry I've not verified it's working on 3.7. Maybe someone else has?

It's still pretty shaky from previous versions so test test before using it
in any prod environment.

Den ons 28 juli 2021 11:09Paloma Martinez ***@***.***> skrev:

**Comment by palomamtnez** [comment]
No worries! 
I  tried it on 3.7 but didn't show up on my entries pages (where I think it should show up?) 
We are planning on designing a solution, not there yet
If we have something worth to share I will post it here!

**Comment by LukssOne** [comment]
Hi @naboo I tested plugin on 3.7.22 and After duplicating action it throw a Not found Exception but it should work. 
Do you plan to release a compatible version?
 
![404](https://user-images.githubusercontent.com/13950592/143533143-1ed596bb-9fb7-40c5-977a-30f793741b2c.png)

**Comment by naboo** [comment]
Sorry @LukssOne I haven't planned on doing anything with it. Feel free to check yourself.

Looking at the error message it seems the new entry isn't found in the site it's been duplicated towards. My guess is that the code isn't duplicating the entry correctly so the new entry doesn't exist in the new site?

**Comment by darylknight** [comment]
I've just installed this and tried to use it to duplicate an entry into a new site and got the same error. Is this plugin abandoned?

**Comment by darylknight** [comment]
Also just tried duplicating a different entry and got a different error message:

![image](https://user-images.githubusercontent.com/1250017/159731702-1bd1fc9a-13ee-4b19-967c-571fce3c2aa1.png)

**Comment by naboo** [comment]
Yeah this is very abandoned at the moment. There's a lot of changes under the hood needed since all the major Craft releases since the last update. I need to pull this Plugin from the store. Will get on that!
